# Generated by Django 5.0.4 on 2024-04-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_works'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='name',
            new_name='question',
        ),
    ]
