# Generated by Django 5.0.4 on 2024-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_consult_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='payment_confirmation',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Confirmed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='consult',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Assigned')], default=0),
        ),
    ]
