# Generated by Django 5.0.4 on 2024-05-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_consult_status_consult_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consult',
            name='checkout_request_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consult',
            name='payment_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
