# Generated by Django 5.0.4 on 2024-05-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_consult_assigned_alter_consult_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
