# Generated by Django 5.0.4 on 2024-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_consult_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
