# Generated by Django 5.0.4 on 2024-05-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_consult_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'access_level': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_consults', to=settings.AUTH_USER_MODEL),
        ),
    ]
