# Generated by Django 5.0.4 on 2024-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_consult_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='task_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
