# Generated by Django 5.0.4 on 2024-05-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_consult_task_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
