# Generated by Django 5.0.4 on 2024-06-03 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('admin_response', models.TextField()),
                ('satisfied', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('response_doc', models.FileField(blank=True, null=True, upload_to='response_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.consult')),
            ],
        ),
    ]
