# Generated by Django 5.0.4 on 2024-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
