# Generated by Django 5.0.4 on 2024-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
