# Generated by Django 5.0.4 on 2024-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag1', models.CharField(max_length=300)),
                ('tag2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag1', models.CharField(max_length=300)),
                ('tag2', models.CharField(max_length=300)),
            ],
        ),
    ]
