# Generated by Django 5.0.4 on 2024-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_how'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
