# Generated by Django 5.0.4 on 2024-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_panel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
