# Generated by Django 5.0.4 on 2024-06-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms',
            old_name='description',
            new_name='descriptions',
        ),
    ]
